# Generated by Django 4.2.9 on 2024-01-29 20:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="BaseModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rcImage",
                    models.ImageField(blank=True, null=True, upload_to="blogs"),
                ),
                (
                    "gridImage",
                    models.ImageField(blank=True, null=True, upload_to="blogs"),
                ),
                (
                    "largeImage",
                    models.ImageField(blank=True, null=True, upload_to="blogs"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.basemodel",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("image", models.ImageField(upload_to="brand")),
                ("url", models.URLField()),
                ("priority", models.IntegerField(default=0)),
            ],
            bases=("api.basemodel",),
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.basemodel",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            bases=("api.basemodel",),
        ),
        migrations.CreateModel(
            name="Fact",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.basemodel",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("number", models.IntegerField(default=0)),
            ],
            bases=("api.basemodel",),
        ),
        migrations.CreateModel(
            name="HomeSlider",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.basemodel",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="slider")),
            ],
            bases=("api.basemodel",),
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.basemodel",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            bases=("api.basemodel",),
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.basemodel",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("photo", models.ImageField(upload_to="team")),
                ("designation", models.CharField(max_length=200)),
                ("order", models.IntegerField(default=0)),
            ],
            bases=("api.basemodel",),
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.basemodel",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                ("body", models.TextField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blog",
                        to="api.author",
                    ),
                ),
                (
                    "media",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog",
                        to="api.media",
                    ),
                ),
                ("tags", models.ManyToManyField(related_name="blogs", to="api.tag")),
            ],
            bases=("api.basemodel",),
        ),
    ]
