# Generated by Django 4.2.9 on 2024-01-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
