# Generated by Django 4.2.9 on 2024-03-28 02:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_message_newsletter"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("education", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ("id",),
                "abstract": False,
            },
        ),
    ]
